version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: bitigchi-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bitigchi_db
      POSTGRES_USER: bitigchi_user
      POSTGRES_PASSWORD: BitigchiDB2024Secure!
    ports:
      - "5432:5432"
    volumes:
      - bitigchi_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bitigchi_user -d bitigchi_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7.0
    container_name: bitigchi-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: bitigchi_admin
      MONGO_INITDB_ROOT_PASSWORD: BitigchiMongo2024Secure!
      MONGO_INITDB_DATABASE: bitigchi_social
    ports:
      - "27017:27017"
    volumes:
      - bitigchi_mongodata:/data/db

  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    container_name: bitigchi-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - bitigchi_miniodata:/data

volumes:
  bitigchi_pgdata:
    driver: local
  bitigchi_mongodata:
    driver: local
  bitigchi_miniodata:
    driver: local
